config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#index'
  get 'answer', to: 'static_pages#show'
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Vous êtes connecté ! Bienvenue sur le site qui vous donnera la réponse à la question de l'univers..."     
      log_in user
      redirect_to user
    else 
   #not working
    	flash.now[:danger] = 'Invalid email/password combination'
    	render 'new'
    end
  end


  def destroy
    log_out
    flash[:danger] = 'Vous êtes bien déconnecté'
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

	def answer
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def index
  end

  def edit
  	@user = User.find(params[:id])

# On interdit à un user de modifier le profil d'un autre user    
    if @user == current_user
      render 'edit'
    else 
      flash.now[:error] = "Petit filou, vous essayez de modifier un profil qui n'est pas le vôtre !"
      render 'show'
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Votre profil a bien été créé ! Bienvenue sur le site qui vous donnera la réponse à la question de l'univers..."

 # On login quand un nouvel user est créé     
      log_in @user
  		redirect_to @user

  	else render 'new'
  	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to @user
  	else render 'edit'
  	end
  end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end

	def show
		@user = User.find(params[:id])
	end

	private
  	def user_params
      params.permit(:name, :email, :password)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end


    def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	 def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: @user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Top Secret", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>

            <% if logged_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Bienvenue sur votre profil, <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Voir mon profil", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Mon site top secret</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= render 'layouts/header' %>

    <div class="yield">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<% if logged_in? %>

<h1> <%= current_user.name %> </h1>

<h2> Bienvenue sur le site qui te donnera la clé de l'univers. </h2>

<p> Tu ne sais pas ce que tu va manger ce soir mais tu veux connaitre la solution de l'univers ? </p>

<p> <%= link_to "Par ici", answer_path, class: "btn btn-success"%> </p>


<% else %>

<h1> Cher visiteur </h1>

<h2> Bienvenue sur le site qui vous donnera la clé de l'univers. </h2>

<p> Vous souhaitez connaître la réponse à la question de l'univers ? </p>

<p> Identifie toi bro ! </p>

<p> <%= link_to "Log in", login_path, class: "btn btn-success" %> </p>


<% end %>

app/views/static_pages/show.html.erb
<h1> Tu pensais que j'allais dire 42 fdp ? </h1>

<p> <%= link_to("Retour à la question de l'univers", root_path) %> </p>

app/views/users/_form.html.erb
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
        <% @user.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
    </div>
  <% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <p> <%= label_tag 'name', "Quel est votre nom ?" %> </p>
  <p> <%= text_field_tag 'name' %> </p>

  <p> <%= label_tag 'email', "Quel est votre email ?" %> </p>
  <p> <%= text_field_tag 'email' %> </p>

  <p> <%= label_tag 'password', "Quel est votre mot de passe ?" %> </p>
  <p> <%= password_field_tag 'password' %> </p>

  </div>
</div>

app/views/users/answer.html.erb
<h1> Tu pensais que j'allais dire 42 fdp ? </h1>

app/views/users/edit.html.erb
<h1> Editer mon profil </h1>

<%= form_tag user_path(@user), method: :put do %>
 
<%= render 'form' %>
 
<div class="row">
  <div class="col-md-6 col-md-offset-3"> 
	<%= submit_tag "Modifier mon profil utilisateur", class: "btn btn-primary" %>
  </div>
</div>

<% end %>

 <p> <%= link_to "Supprimer le profil", user_path(@user),
              method: :delete,
              data: { confirm: 'Etes-vous sûr ?' } %> </p>

app/views/users/new.html.erb
<h1> Créer un nouvel utilisateur </h1>

<%= form_tag (users_path) do %>
 
<%= render 'form' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<p> <%= submit_tag 'Je crée un utilisateur', class: "btn btn-primary"%></p>

  </div>
</div>

<% end %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p> <%= link_to('Editer mon profil', edit_user_path) %> </p> 